export const shows = [
  {
    date: "4/5/2025",
    venue: "Riverbillies",
    city: "Gibraltar",
    state: "MI",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    isPrivate: false,
    eventLink: "",
  },
  {
    date: "5/9/2025",
    venue: "Sandbar Grille",
    city: "LaSalle",
    state: "MI",
    startTime: "8:30 PM",
    endTime: "12:30 AM",
    isPrivate: false,
    eventLink: "",
  },
  {
    date: "5/30/2025",
    venue: "Riverbillies",
    city: "Gibraltar",
    state: "MI",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    isPrivate: false,
    eventLink: "",
  },
  {
    date: "6/20/2025",
    venue: "Riverbillies",
    city: "Gibraltar",
    state: "MI",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    isPrivate: false,
    eventLink: "",
  },
  {
    date: "6/21/2025",
    venue: "Sandbar Grille",
    city: "LaSalle",
    state: "MI",
    startTime: "8:30 PM",
    endTime: "12:30 AM",
    isPrivate: false,
    eventLink: "",
  },
  {
    date: "7/12/2025",
    venue: "Original Gravity Brewing Co",
    city: "Milan",
    state: "MI",
    startTime: "4:00 PM",
    endTime: "7:00 PM",
    isPrivate: false,
    eventLink: "https://fb.me/e/4vYE3YLKv",
  },
  {
    date: "7/19/2025",
    venue: "VFW",
    city: "Brownstown",
    state: "MI",
    startTime: "",
    endTime: "",
    isPrivate: true,
    eventLink: "",
  },
  {
    date: "8/1/2025",
    venue: "Riverbillies",
    city: "Gibraltar",
    state: "MI",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    isPrivate: false,
    eventLink: "https://fb.me/e/4jcoAc8Sx",
  },
  {
    date: "8/23/2025",
    venue: "Riverbillies",
    city: "Gibraltar",
    state: "MI",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    isPrivate: false,
    eventLink: "https://fb.me/e/9HR8VqORv",
  },
  {
    date: "9/12/2025",
    venue: "FEDCO",
    city: "Monroe",
    state: "MI",
    startTime: "",
    endTime: "",
    isPrivate: true,
    eventLink: "",
  },
  {
    date: "9/13/2025",
    venue: "Sandbar Grille",
    city: "LaSalle",
    state: "MI",
    startTime: "8:30 PM",
    endTime: "12:30 AM",
    isPrivate: false,
    eventLink: "https://fb.me/e/4kGrMlpwI",
  },
  {
    date: "9/19/2025",
    venue: "Pumpkin Festival",
    city: "Romulus",
    state: "MI",
    startTime: "6:00 PM",
    endTime: "8:00 PM",
    isPrivate: false,
    eventLink: "https://fb.me/e/8rqiPIxqJ",
  },
  {
    date: "10/17/2025",
    venue: "Hell Saloon",
    city: "Hell",
    state: "MI",
    startTime: "8:00 PM",
    endTime: "11:59 PM",
    isPrivate: false,
    eventLink: "https://fb.me/e/5Pvu2XkIP",
  },
  {
    date: "10/24/2025",
    venue: "Riverbillies",
    city: "Gibraltar",
    state: "MI",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    isPrivate: false,
    eventLink: "https://fb.me/e/4O38uYBcy",
  },
  {
    date: "11/28/2025",
    venue: "Hell Saloon",
    city: "Hell",
    state: "MI",
    startTime: "8:00 PM",
    endTime: "11:59 PM",
    isPrivate: false,
    eventLink: "https://fb.me/e/8EFLWLk4v",
  },
  {
    date: "12/12/2025",
    venue: "Hell Saloon",
    city: "Hell",
    state: "MI",
    startTime: "8:00 PM",
    endTime: "11:59 PM",
    isPrivate: false,
    eventLink: "https://fb.me/e/38NuvVM0w",
  },
];